"use client"

import { useEffect, useState } from "react"
import type { CharacterState } from "@/types"

// "Madam" — the app's 3D African-teacher mascot (modelled on madam.png). Each
// state is a short flip-book of transparent PNG poses generated by
// scripts/gen-3d-character.py; flipping through them makes the still frames read
// as one figure moving (welcoming, pointing, celebrating, looking sad...).
// Replaces the old Lottie rig.

const BASE = "/images/character/3d"

// How fast each state's flip-book cycles (ms per frame). Livelier moods flip
// faster; calm/instructional states breathe slowly so the teacher never looks
// jittery while she is talking.
const FRAME_MS: Partial<Record<CharacterState, number>> = {
  welcome: 700,
  idle: 1100,
  watching: 950,
  teaching: 850,
  pointing: 900,
  sad: 1000,
  nom_nom: 400,
  happy: 550,
  excited: 350,
  celebrating: 380,
}
const DEFAULT_MS = 500

// manifest.json maps each state to how many frames were generated for it.
type Manifest = Partial<Record<CharacterState, number>>

// Fetched once per session and shared across every mounted character.
let manifestPromise: Promise<Manifest> | null = null
function loadManifest(): Promise<Manifest> {
  if (!manifestPromise) {
    manifestPromise = fetch(`${BASE}/manifest.json`)
      .then((r) => (r.ok ? (r.json() as Promise<Manifest>) : {}))
      .catch(() => ({}))
  }
  return manifestPromise
}

const framePath = (state: CharacterState, n: number) => `${BASE}/${state}-${n}.png`

// Warm the browser cache for a state's frames so the flip-book never flashes a
// half-loaded pose.
const preloaded = new Set<string>()
function preload(state: CharacterState, count: number) {
  for (let n = 1; n <= count; n++) {
    const src = framePath(state, n)
    if (preloaded.has(src)) continue
    preloaded.add(src)
    const img = new Image()
    img.src = src
  }
}

interface Character3DProps {
  state: CharacterState
  /** Pixel size, or a CSS length ("100%" to fill a responsive parent). */
  size?: number | string
  /** When false, show a single still pose (frame 1) with no flip-book or
   *  cross-fade. Used on the landing page for a calm, static welcome. */
  animate?: boolean
  /** Hold ONE specific frame of the state (1-based) instead of flipping.
   *  e.g. pointing frame 2 is the horizontal arm — held still while the voice
   *  names the letter, so the gesture stays aimed at what is being named. */
  pose?: number
  /** Mirror the character horizontally. The generated poses face/point LEFT;
   *  set flip when whatever she is pointing at is on her RIGHT. */
  flip?: boolean
  /** Cap the flip-book to the first N frames of this state (e.g. 2) instead of
   *  every generated pose — a slower, calmer loop for a held introduction. */
  maxFrames?: number
  /** Override this state's default ms-per-frame (see FRAME_MS) for one call
   *  site, without changing the pace everywhere else that state is used. */
  frameMs?: number
}

export function Character3D({ state, size = 200, animate = true, pose, flip, maxFrames, frameMs }: Character3DProps) {
  const [count, setCount] = useState(0)
  const [frame, setFrame] = useState(0)

  // Resolve how many frames this state has (from the manifest), and preload them.
  useEffect(() => {
    let active = true
    loadManifest().then((m) => {
      if (!active) return
      const c = Math.min(m[state] ?? 0, maxFrames ?? Infinity)
      // Still mode only ever shows frame 1, so there's no need to preload the rest.
      if (c > 0) preload(state, animate ? c : 1)
      setCount(c)
      setFrame(0)
    })
    return () => {
      active = false
    }
  }, [state, animate, maxFrames])

  // Flip through the frames on a per-state interval, looping forever.
  useEffect(() => {
    if (!animate || pose != null || count <= 1) return
    const id = setInterval(
      () => setFrame((f) => (f + 1) % count),
      frameMs ?? FRAME_MS[state] ?? DEFAULT_MS,
    )
    return () => clearInterval(id)
  }, [animate, pose, count, state, frameMs])

  const flipStyle = flip ? { transform: "scaleX(-1)" } : undefined

  if (count === 0) {
    // Frames not generated yet (or manifest missing) — reserve the space rather
    // than substituting an emoji "face" for the character.
    return <div aria-hidden style={{ width: size, height: size }} />
  }

  if (!animate || pose != null) {
    // Single still pose — no stacked frames, no opacity transition.
    const n = pose != null ? Math.min(Math.max(1, pose), count) : 1
    return (
      <img
        src={framePath(state, n)}
        alt=""
        draggable={false}
        aria-hidden
        className="pointer-events-none select-none object-contain"
        style={{ width: size, height: size, ...flipStyle }}
      />
    )
  }

  // All frames are stacked; only the current one is opaque. Cross-fading (rather
  // than hard-swapping src) hides any small pose-to-pose jump and keeps motion
  // smooth even while a frame is still decoding.
  return (
    <div
      className="relative select-none"
      style={{ width: size, height: size, ...flipStyle }}
      aria-hidden
    >
      {Array.from({ length: count }, (_, i) => (
        <img
          key={i}
          src={framePath(state, i + 1)}
          alt=""
          draggable={false}
          className="pointer-events-none absolute inset-0 h-full w-full object-contain transition-opacity duration-300 ease-in-out"
          style={{ opacity: i === frame ? 1 : 0 }}
        />
      ))}
    </div>
  )
}
