import { actionImagesFor } from "@/lib/wordImages"

// Resolves the "See & Know" voice line for a discovery word, for the ALL-tour
// (data/letterImages.ts + components/discover/DiscoverGallery.tsx). Every word
// gets a "This is a/an X" introduction line; only words with a real action
// image (lib/wordImages ACTIONS) also get a follow-up action line — recordings
// live under /public/audio/discover, generated by scripts/gen-discover-tour-audio.py.

const ID_OVERRIDES: Record<string, string> = {
  "ice cream": "icecream",
  "x-ray": "xray",
}

const slug = (s: string) => s.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "")

function discoverId(word: string): string {
  return ID_OVERRIDES[word.toLowerCase()] ?? slug(word)
}

/** "This is a/an {word}." — played by the teacher before the picture is shown. */
export function aloneAudioFor(word: string): string {
  return `/audio/discover/${discoverId(word)}-alone.mp3`
}

/** The word's action-scene line — only when it actually has an action image. */
export function actionAudioFor(word: string): string | undefined {
  return actionImagesFor(word).length > 0 ? `/audio/discover/${discoverId(word)}-action.mp3` : undefined
}
