// Maps a word/label to a real image file under /public/images. Used as the
// second choice in <Picture> (after the data's own `src`, before the emoji
// fallback) so games show real artwork wherever one exists and stay playable
// with emoji where one does not.
//
// The library is organised for the whole project (see scripts/organize-images.py):
//   /images/things/{name}.png   one canonical TRANSPARENT picture per thing
//   /images/actions/{name}.png  that thing IN ACTION (scene, background kept)
// To add art for a new word: drop {name}.png into things/ (and optionally an
// action scene into actions/), then add a line here.

const IMAGES: Record<string, string> = {
  "airplane": "/images/things/airplane.png",
  "ant": "/images/things/ant.png",
  "antelope": "/images/things/antelope.png",
  "apple": "/images/things/apple.png",
  "avocado": "/images/things/avocado.png",
  "ball": "/images/things/ball.png",
  "banana": "/images/things/banana.png",
  "bear": "/images/things/bear.png",
  "bed": "/images/things/bed.png",
  "bee": "/images/things/bee.png",
  "bird": "/images/things/bird.png",
  "bread": "/images/things/bread.png",
  "butterfly": "/images/things/butterfly.png",
  "cabbage": "/images/things/cabbage.png",
  "candy": "/images/things/candy.png",
  "car": "/images/things/car.png",
  "cassava": "/images/things/cassava.png",
  "cat": "/images/things/cat.png",
  "cheese": "/images/things/cheese.png",
  "chocolate": "/images/things/chocolate.png",
  "coconut": "/images/things/coconut.png",
  "cow": "/images/things/cow.png",
  "crocodile": "/images/things/crocodile.png",
  "cucumber": "/images/things/cucumber.png",
  "cup": "/images/things/cup.png",
  "dog": "/images/things/dog.png",
  "dolphin": "/images/things/dolphin.png",
  "donkey": "/images/things/donkey.png",
  "door": "/images/things/door.png",
  "duck": "/images/things/duck.png",
  "eagle": "/images/things/eagle.png",
  "egg": "/images/things/egg.png",
  "elephant": "/images/things/elephant.png",
  "fish": "/images/things/fish.png",
  "fishing net": "/images/things/fishing-net.png",
  "flamingo": "/images/things/flamingo.png",
  "flower": "/images/things/flower.png",
  "fox": "/images/things/fox.png",
  "frog": "/images/things/frog.png",
  "gate": "/images/things/gate.png",
  "giraffe": "/images/things/giraffe.png",
  "glass": "/images/things/glass.png",
  "goat": "/images/things/goat.png",
  "goose": "/images/things/goose.png",
  "gorilla": "/images/things/gorilla.png",
  "guava": "/images/things/guava.png",
  "hat": "/images/things/hat.png",
  "hen": "/images/things/hen.png",
  "hippopotamus": "/images/things/hippopotamus.png",
  "honey": "/images/things/honey.png",
  "horse": "/images/things/horse.png",
  "house": "/images/things/house.png",
  "hyena": "/images/things/hyena.png",
  "icecream": "/images/things/icecream.png",
  "iguana": "/images/things/iguana.png",
  "jacket": "/images/things/jacket.png",
  "jaguar": "/images/things/jaguar.png",
  "jellyfish": "/images/things/jellyfish.png",
  "juice": "/images/things/juice.png",
  "kangaroo": "/images/things/kangaroo.png",
  "key": "/images/things/key.png",
  "kite": "/images/things/kite.png",
  "kitten": "/images/things/kitten.png",
  "koala": "/images/things/koala.png",
  "lamb": "/images/things/lamb.png",
  "lemon": "/images/things/lemon.png",
  "leopard": "/images/things/leopard.png",
  "lion": "/images/things/lion.png",
  "lizard": "/images/things/lizard.png",
  "lollipop": "/images/things/lollipop.png",
  "mango": "/images/things/mango.png",
  "milk": "/images/things/milk.png",
  "mosquito": "/images/things/mosquito.png",
  "net": "/images/things/net.png",
  "mouse": "/images/things/mouse.png",
  "newt": "/images/things/newt.png",
  "octopus": "/images/things/octopus.png",
  "oil": "/images/things/oil.png",
  "orange": "/images/things/orange.png",
  "ostrich": "/images/things/ostrich.png",
  "owl": "/images/things/owl.png",
  "papaya": "/images/things/papaya.png",
  "parrot": "/images/things/parrot.png",
  "pen": "/images/things/pen.png",
  "penguin": "/images/things/penguin.png",
  "pineapple": "/images/things/pineapple.png",
  "puppy": "/images/things/puppy.png",
  "quacker": "/images/things/quacker.png",
  "quail": "/images/things/quail.png",
  "queen": "/images/things/queen.png",
  "rabbit": "/images/things/rabbit.png",
  "rat": "/images/things/rat.png",
  "rhinoceros": "/images/things/rhinoceros.png",
  "rice": "/images/things/rice.png",
  "rooster": "/images/things/rooster.png",
  "salt": "/images/things/salt.png",
  "sheep": "/images/things/sheep.png",
  "shoe": "/images/things/shoe.png",
  "snail": "/images/things/snail.png",
  "snake": "/images/things/snake.png",
  "spider": "/images/things/spider.png",
  "spoon": "/images/things/spoon.png",
  "sugar": "/images/things/sugar.png",
  "sun": "/images/things/sun.jpg",
  "sweet potato": "/images/things/sweet-potato.png",
  "table": "/images/things/table.png",
  "tea": "/images/things/tea.png",
  "tiger": "/images/things/tiger.png",
  "toad": "/images/things/toad.png",
  "tomato": "/images/things/tomato.png",
  "toothbrush": "/images/things/toothbrush.png",
  "tree": "/images/things/tree.png",
  "turkey": "/images/things/turkey.png",
  "turtle": "/images/things/turtle.png",
  "umbrella": "/images/things/umbrella.png",
  "unicorn fish": "/images/things/unicorn-fish.png",
  "urial": "/images/things/urial.png",
  "van": "/images/things/van.png",
  "vervet monkey": "/images/things/vervet-monkey.png",
  "viper": "/images/things/viper.png",
  "vole": "/images/things/vole.png",
  "vulture": "/images/things/vulture.png",
  "warthog": "/images/things/warthog.png",
  "wasp": "/images/things/wasp.png",
  "water": "/images/things/water.png",
  "watermelon": "/images/things/watermelon.jpg",
  "whale": "/images/things/whale.png",
  "window": "/images/things/window.png",
  "wolf": "/images/things/wolf.png",
  "x ray": "/images/things/x-ray.png",
  "xylocopa": "/images/things/xylocopa.png",
  "yak": "/images/things/yak.png",
  "yam": "/images/things/yam.png",
  "yellow tail": "/images/things/yellow-tail.png",
  "yogurt": "/images/things/yogurt.png",
  "yolk": "/images/things/yolk.png",
  "zebra": "/images/things/zebra.png",
  "zip": "/images/things/zip.png",
  "zonkey": "/images/things/zonkey.png",
  "zorro": "/images/things/zorro.png",
  "chicken": "/images/things/hen.png",
  "ice cream": "/images/things/icecream.png",
}

// Extra shots of the same thing, tried after the canonical image.
const ALTERNATES: Record<string, string[]> = {
  "antelope": ["/images/things/antelope-2.png"],
  "flower": ["/images/things/flower-2.png"],
  "net": ["/images/things/net.png"],
  "sun": ["/images/things/sun-2.png"],
  "tomato": ["/images/things/tomato-2.png"],
  "toothbrush": ["/images/things/toothbrush-2.png"],
  "water": ["/images/things/water-2.png", "/images/things/water-3.png"],
  "watermelon": ["/images/things/watermelon-2.png"],
}

// "The thing in action" scenes, shown right after the thing itself so the
// child links the object to what it does (lollipop -> eating a lollipop).
const ACTIONS: Record<string, string[]> = {
  "airplane": ["/images/actions/passanger-airplane.jpg"],
  "ant": ["/images/actions/ant-working.jpg"],
  "apple": ["/images/actions/eat-apple.jpg"],
  "ball": ["/images/actions/playing-ball.jpg"],
  "banana": ["/images/actions/monkey-eat-banana.jpg"],
  "bed": ["/images/actions/child-laying-bed.jpg"],
  "bird": ["/images/actions/bird-sit-on-tree.jpg"],
  "bread": ["/images/actions/eat-bread.jpg"],
  "car": ["/images/actions/father-drive-car.jpg"],
  "cat": ["/images/actions/cat-drink-milk.jpg"],
  "chicken": ["/images/actions/cook-chicken.jpg"],
  "chocolate": ["/images/actions/eat-chocolate.jpg"],
  "coconut": ["/images/actions/man-cut-coconut.jpg"],
  "dog": ["/images/actions/barking-dog.jpg"],
  "door": ["/images/actions/girl-open-door.jpg"],
  "duck": ["/images/actions/duck-swim.jpg"],
  "egg": ["/images/actions/cook-egg.jpg"],
  "elephant":["/images/actions/elephant-uproot-tree.jpg"],
  "fish": ["/images/actions/swim-fish.jpg"],
  "fishing net": ["/images/actions/men-fishing-net.jpg"],
  "flower": ["/images/actions/child-plant-flower.jpg"],
  "frog": ["/images/actions/frog-eat-fly.jpg"],
  "gate": ["/images/actions/open-gate.jpg"],
  "glass": ["/images/actions/glass-receive-milk.jpg"],
  "goat": ["/images/actions/goat-eat-grass.jpg"],
  "guava": ["/images/actions/eat-guava.jpg"],
  "hat": ["/images/actions/grandpa-hat.jpg"],
  "hen": ["/images/actions/hen-eat-worm.jpg"],
  "house": ["/images/actions/man-build-house.jpg"],
  "ice cream": ["/images/actions/eat-icecream.jpg"],
  "jacket": ["/images/actions/wearing-jacket.jpg"],
  "juice": ["/images/actions/drink-juice.jpg"],
  "key": ["/images/actions/open-door-key.jpg"],
  "kite": ["/images/actions/children-flying-kite.jpg"],
  "lion": ["/images/actions/lion-roar.jpg"],
  "lollipop": ["/images/actions/eat-lollipop.png"],
  "mango": ["/images/actions/eat-mango.jpg"],
  "milk": ["/images/actions/drink-milk.jpg"],
  "net": ["/images/actions/men-fishing-net.jpg"],
  "owl": ["/images/actions/owl-fly.jpg"],
  "orange": ["/images/actions/eat-orange.jpg"],
  "papaya": ["/images/actions/mother-prepare-papaya.jpg"],
  "pen": ["/images/actions/boy-writing-pen.jpg"],
  "pineapple": ["/images/actions/eat-pineapple.png"],
  "queen": ["/images/actions/queen-on-throne-chair.jpg"],
  "rabbit": ["/images/actions/rabbit-eat.jpg"],
  "rice": ["/images/actions/family-eat-rice.jpg"],
  "shoe": ["/images/actions/child-weared-shoes.jpg"],
  "sun": ["/images/actions/sun-shining.jpg"],
  "spoon": [ "/images/actions/spoon-carry-icecream.jpg"],
  "table": ["/images/actions/father-creating-table.jpg"],
  "tea": ["/images/actions/child-drink-tea.jpg"],
  "tomato": ["/images/actions/mother-cutting-tomatoes.jpg"],
  "toothbrush": ["/images/actions/brushing-tooth.jpg"],
  "tree": ["/images/actions/tree-hold-bird-squirrel.jpg"],
  "umbrella": ["/images/actions/child-umbrella.jpg"],
  "van": ["/images/actions/van-people.jpg"],
  "water": ["/images/actions/drink-water.jpg"],
  "watermelon": ["/images/actions/eat-watermelon.jpg"],
  "window": ["/images/actions/mother-open-window.jpg"],
  "x ray": ["/images/actions/docter-puppy-x-ray.jpg"],
  "yam": ["/images/actions/cut-yam.jpg"],
  "yolk": ["/images/actions/yolk-fry.jpg"],
  "zebra": ["/images/actions/zebra-playing.jpg"],
  "zip": ["/images/actions/child-closing-zip.jpg"],
}

const normalize = (label: string) => label.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim()

/** Best-effort real image for a label. Returns undefined if none is available. */
export function imageFor(label?: string): string | undefined {
  if (!label) return undefined
  const norm = normalize(label)
  return IMAGES[norm] ?? IMAGES[norm.split(" ")[0]]
}

/** Alternate shots of the same thing, tried after the canonical image. */
export function imageAlternatesFor(label?: string): string[] {
  if (!label) return []
  const norm = normalize(label)
  return ALTERNATES[norm] ?? ALTERNATES[norm.split(" ")[0]] ?? []
}

/** Scenes of the thing in action, shown after the thing itself. */
export function actionImagesFor(label?: string): string[] {
  if (!label) return []
  const norm = normalize(label)
  return ACTIONS[norm] ?? ACTIONS[norm.split(" ")[0]] ?? []
}
